apiVersion: apps/v1
kind: Deployment
metadata:
  name: plan-meeting
  labels:
    app: plan-meeting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plan-meeting
  template:
    metadata:
      labels:
        app: plan-meeting
    spec:
      containers:
        - name: plan-meeting
          env:
            - name: NEXT_SERVICE
              value: book-flights
          image: leszko/propeller-demo
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: plan-meeting
spec:
  type: LoadBalancer
  selector:
    app: plan-meeting
  ports:
    - port: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-flights
  labels:
    app: book-flights
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-flights
  template:
    metadata:
      labels:
        app: book-flights
    spec:
      containers:
        - name: book-flights
          env:
            - name: NEXT_SERVICE
              value: book-hotel
          image: leszko/propeller-demo
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: book-flights
spec:
  type: ClusterIP
  selector:
    app: book-flights
  ports:
    - port: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-hotel
  labels:
    app: book-hotel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-hotel
  template:
    metadata:
      labels:
        app: book-hotel
    spec:
      containers:
        - name: book-hotel
          env:
            - name: NEXT_SERVICE
              value: book-transport
          image: leszko/propeller-demo
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: book-hotel
spec:
  type: ClusterIP
  selector:
    app: book-hotel
  ports:
    - port: 8080


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-transport
  labels:
    app: book-transport
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-transport
  template:
    metadata:
      labels:
        app: book-transport
    spec:
      containers:
        - name: book-transport
          env:
            - name: SHOULD_FAIL
              value: "true"
          image: leszko/propeller-demo
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: book-transport
spec:
  type: ClusterIP
  selector:
    app: book-transport
  ports:
    - port: 8080